In [1]:
import pandas as pd

In [7]:
df = pd.read_csv("raw_data.csv", encoding="latin1")

In [8]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [9]:
df.duplicated().sum()

np.int64(5268)

In [10]:
df = df.drop_duplicates()

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [13]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [14]:
df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [16]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [17]:
df["InvoiceDate"].dtype

dtype('<M8[ns]')

In [18]:
(df["Quantity"]<0).sum()

np.int64(10587)

In [20]:
df[df["Quantity"]<0][["InvoiceNo","Quantity","Description"]].head(20)

     InvoiceNo  Quantity                          Description
141    C536379        -1                             Discount
154    C536383        -1      SET OF 3 COLOURED  FLYING DUCKS
235    C536391       -12       PLASTERS IN TIN CIRCUS PARADE
236    C536391       -24     PACK OF 12 PINK PAISLEY TISSUES
237    C536391       -24     PACK OF 12 BLUE PAISLEY TISSUES
238    C536391       -24    PACK OF 12 RED RETROSPOT TISSUES
239    C536391       -12          CHICK GREY HOT WATER BOTTLE
240    C536391       -12     PLASTERS IN TIN VINTAGE PAISLEY
241    C536391       -24               PLASTERS IN TIN SKULLS
939    C536506        -6             JAM MAKING SET WITH JARS
1441   C536543        -1            HAND WARMER RED RETROSPOT
1442   C536543        -2            CHARLOTTE BAG SUKI DESIGN
1973   C536548        -4           3 HOOK HANGER MAGIC GARDEN
1974   C536548        -5        5 HOOK HANGER MAGIC TOADSTOOL
1975   C536548        -1  SET/5 RED RETROSPOT LID GLASS BOWLS
1976   C536548        -7    SET OF SALT AND PEPPER TOADSTOOLS
1977   C536548        -1                   DELUXE SEWING KIT
1978   C536548        -2          TRIPLE PHOTO FRAME CORNICE
1979   C536548        -1    RETROSPOT PARTY BAG + STICKER SET
1980   C536548        -2         HOOK, 1 HANGER ,MAGIC GARDEN

In [22]:
df["Description"] = df["Description"].str.strip().str.upper()

In [23]:
df["Country"] = df["Country"].str.strip().str.upper()

In [25]:
df.to_csv("cleaned_data.csv",index=False)