In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("cleaned_data.csv")

In [7]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [8]:
import sqlite3

In [9]:
conn = sqlite3.connect("analysis.db")

In [10]:
df.to_sql("sales",conn,if_exists="replace",index=False)

536641

In [25]:
query = "SELECT * FROM sales LIMIT 20;"

In [26]:
result = pd.read_sql(query, conn)

In [27]:
result

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,2010-12-01 08:34:00,3.75,13047.0,United Kingdom
13,536367,22310,IVORY KNITTED MUG COSY,6,2010-12-01 08:34:00,1.65,13047.0,United Kingdom
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,2010-12-01 08:34:00,9.95,13047.0,United Kingdom
17,536367,21754,HOME BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom
18,536367,21755,LOVE BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom
19,536367,21777,RECIPE BOX WITH METAL HEART,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom

In [37]:
df.shape

(536641, 8)

In [40]:
query = "SELECT Country, SUM(Quantity * Unitprice) AS total_revenue FROM sales Group by country order by total_Revenue DESc Limit 10;"

In [41]:
result = pd.read_sql(query, conn)

In [42]:
result

          Country  total_revenue
0  United Kingdom   8.167128e+06
1     Netherlands   2.846615e+05
2            EIRE   2.629934e+05
3         Germany   2.215095e+05
4          France   1.973171e+05
5       Australia   1.370098e+05
6     Switzerland   5.636305e+04
7           Spain   5.475603e+04
8         Belgium   4.091096e+04
9          Sweden   3.658541e+04

In [56]:
query = " SELECT strftime('%H', InvoiceDate) AS hour,COUNT(*) AS purchases FROM sales GROUP BY hour ORDER BY purchases DESC;"

In [45]:
result

   hour  purchases
0    12      77573
1    15      76938
2    13      71247
3    14      66572
4    11      56949
5    16      54134
6    10      48808
7    09      34314
8    17      28371
9    08       8906
10   18       7941
11   19       3617
12   20        847
13   07        383
14   06         41

In [53]:
query = " SELECT CustomerID,COUNT(DISTINCT InvoiceNo) AS orders FROM sales WHERE CustomerID IS NOT NULL GROUP BY CustomerID;"

In [54]:
result = pd.read_sql(query, conn)

In [55]:
result

      CustomerID  orders
0        12346.0       2
1        12347.0       7
2        12348.0       4
3        12349.0       1
4        12350.0       1
...          ...     ...
4367     18280.0       1
4368     18281.0       1
4369     18282.0       3
4370     18283.0      16
4371     18287.0       3

[4372 rows x 2 columns]

In [57]:
query = "SELECT AVG(basket_size) AS average_basket_size FROM (SELECT InvoiceNo, SUM(Quantity) AS basket_size FROM sales GROUP BY InvoiceNo);"

In [58]:
result = pd.read_sql(query, conn)

In [59]:
result

   average_basket_size
0           199.324402

In [61]:
query = "SELECT strftime('%Y-%m', InvoiceDate) AS month,SUM(Quantity * UnitPrice) AS revenue FROM sales GROUP BY month ORDER BY month;"

In [62]:
result = pd.read_sql(query, conn)

In [63]:
result

      month      revenue
0   2010-12   746723.610
1   2011-01   558448.560
2   2011-02   497026.410
3   2011-03   682013.980
4   2011-04   492367.841
5   2011-05   722094.100
6   2011-06   689977.230
7   2011-07   680156.991
8   2011-08   681386.460
9   2011-09  1017596.682
10  2011-10  1069368.230
11  2011-11  1456145.800
12  2011-12   432701.060

In [64]:
import os

print(os.getcwd())
print(os.path.abspath("analysis.db"))
print(os.path.exists("analysis.db"))

C:\Users\priya
C:\Users\priya\analysis.db
True